# Generated by Django 4.1 on 2024-10-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0024_fishinfo_age_fishinfo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinfo',
            name='age',
            field=models.CharField(blank=True, choices=[('1', '１ヵ月未満'), ('2', '１～３ヵ月'), ('3', '３～６ヵ月'), ('4', '６～１２ヵ月'), ('5', '１年以上'), ('6', '２年以上'), ('7', '３年以上'), ('8', '５年以上'), ('9', '７年以上'), ('10', '１０年以上'), ('11', '不明')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fishinfo',
            name='location',
            field=models.CharField(blank=True, choices=[('1', '自宅'), ('2', 'ペットショップ'), ('3', '水族館'), ('4', 'その他')], max_length=20, null=True),
        ),
    ]
