# Generated by Django 4.1 on 2024-11-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0028_alter_fishinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinfo',
            name='fish_size',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
