# Generated by Django 4.1 on 2024-11-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0029_alter_fishinfo_fish_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinfo',
            name='aquarium_size',
            field=models.CharField(blank=True, choices=[('1', '60'), ('2', '20'), ('3', '30'), ('4', '45'), ('5', '70'), ('6', '90'), ('7', '100'), ('8', '120'), ('9', '150'), ('10', '180'), ('11', '200'), ('12', '240'), ('13', '300'), ('14', '400'), ('15', '500'), ('15', '700'), ('16', '1000'), ('17', '2000')], max_length=20, null=True),
        ),
    ]
