# Generated by Django 4.1 on 2024-11-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0030_alter_fishinfo_aquarium_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinfo',
            name='fish_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
